export const DELETE_BLOG = 'DELETE_BLOG';
export const FETCH_ALL_BLOG = 'FETCH_ALL_BLOG';
export const UPDATE_BLOG = 'UPDATE_BLOG';
export const CREATE_BLOG = 'CREATE_BLOG';

export const DELETE_PROJECT = 'DELETE_PROJECT';
export const FETCH_ALL_PROJECT = 'FETCH_ALL_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT'

export const DELETE_QUESTION = 'DELETE_QUESTION';
export const FETCH_ALL_QUESTION = 'FETCH_ALL_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const CREATE_QUESTION = 'CREATE_QUESTION'

export const DELETE_QUOTE = 'DELETE_QUOTE';
export const FETCH_ALL_QUOTE = 'FETCH_ALL_QUOTE';
export const UPDATE_QUOTE = 'UPDATE_QUOTE';
export const CREATE_QUOTE = 'CREATE_QUOTE'
